apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredLabels
metadata:
  name: ml-model-governance
  annotations:
    description: "Enforce ML model tracking and cost attribution"
    enforcement: "deny"
spec:
  enforcementAction: deny
  match:
    kinds:
    - apiGroups: ["apps", "batch"]
      kinds: ["Deployment", "StatefulSet", "Job"]
    namespaces: ["default", "ml-production", "ml-staging"]
    labelSelector:
      matchExpressions:
      - key: workload-type
        operator: In
        values: ["ml-inference", "ml-training", "ml-pipeline"]
  parameters:
    labels:
      - "app"              # Application identifier
      - "model-version"    # ML model version (v1.0.0, v2.1.3)
      - "ml-team"          # Team ownership (nlp-team, cv-team, platform)
    message: "ML governance requires model tracking labels"