apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredLabels
metadata:
  name: ml-model-governance
  annotations:
    description: "Enforce ML model tracking and cost attribution"
    enforcement: "deny"
spec:
  enforcementAction: deny
  match:
    kinds:
    - apiGroups: ["apps"]
      kinds: ["Deployment"]
    namespaces: ["default"]
    # NO labelSelector - applies to ALL deployments
  parameters:
    labels:
      - "app"
      - "model-version"
      - "ml-team"
    message: "ML governance requires model tracking labels"