apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8srequiredlabels
spec:
  crd:
    spec:
      names:
        kind: K8sRequiredLabels
      validation:
        openAPIV3Schema:
          type: object
          properties:
            labels:
              type: array
              items:
                type: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8srequiredlabels
        
        violation[{"msg": msg}] {
          required := input.parameters.labels
          provided := input.review.object.metadata.labels
          missing := [label | required[_] = label; not provided[label]]
          count(missing) > 0
          msg := sprintf("\n❌ DEPLOYMENT BLOCKED - Governance Policy Violation\n   Deployment: '%v'\n   Missing Labels: %v\n   Required Labels: %v\n   Reason: All deployments must have proper labels for cost tracking and ownership", [input.review.object.metadata.name, missing, required])
        }