# Invalid AI Workload - Violates multiple OPA policies
# This manifest will be REJECTED by admission control

apiVersion: apps/v1
kind: Deployment
metadata:
  name: facial-recognition-model
  namespace: production  # ❌ Production without approval
  labels:
    app: facial-recognition
    app-type: ml-model
    ai-risk-level: high  # ❌ High risk without oversight
    # ❌ MISSING: team, model-version, model-framework
    # ❌ MISSING: data-classification, cost-center
  annotations:
    # ❌ MISSING: model-registry-url (deploying from Docker Hub)
    # ❌ MISSING: approved-by
    # ❌ MISSING: prometheus.io/scrape
    # ❌ MISSING: gdpr-compliant annotations
    # ❌ MISSING: human-oversight-enabled (required for high-risk)
spec:
  replicas: 5
  selector:
    matchLabels:
      app: facial-recognition
  template:
    metadata:
      labels:
        app: facial-recognition
    spec:
      # ❌ MISSING: priorityClassName
      # ❌ Running as root (no securityContext)
      hostNetwork: true  # ❌ Using host network
      containers:
      - name: model-server
        image: dockerhub.io/random-user/facial-model:latest  # ❌ Not from registry
        ports:
        - containerPort: 8080
        env:
        - name: S3_BUCKET  # ❌ External data without approval
          value: "s3://external-faces-data"
        - name: API_KEY
          value: "hardcoded-secret-key"  # ❌ Hardcoded secret
        resources:
          requests:
            memory: "16Gi"
            cpu: "8"
            nvidia.com/gpu: "4"  # ❌ Requesting 4 GPUs without justification
          # ❌ MISSING: limits (GPU limits don't match requests)
        securityContext:
          privileged: true  # ❌ Privileged container in production
          runAsUser: 0  # ❌ Running as root
        volumeMounts:
        - name: host-data
          mountPath: /data
      volumes:
      - name: host-data
        hostPath:  # ❌ Using hostPath volume
          path: /var/lib/sensitive-data
      nodeSelector:
        gpu-type: a100  # ❌ Using expensive A100 in production without justification

---
# Another invalid deployment - wrong team in namespace
apiVersion: apps/v1
kind: Deployment
metadata:
  name: experiment-job
  namespace: ml-training  # Owned by data-science-team
  labels:
    app: experiment
    team: research-team  # ❌ Wrong team for this namespace
    app-type: ml-model
    data-classification: restricted  # ❌ PII without encryption
  annotations:
    # ❌ MISSING: storage-encryption-enabled for PII
    # ❌ MISSING: dpo-approved for restricted data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: experiment
  template:
    metadata:
      labels:
        app: experiment
    spec:
      containers:
      - name: training
        image: tensorflow/tensorflow:latest-gpu
        resources:
          requests:
            nvidia.com/gpu: "10"  # ❌ Exceeds namespace quota (max 8)
            memory: "128Gi"
            cpu: "32"
          limits:
            nvidia.com/gpu: "12"  # ❌ Limits don't match requests

---
# Invalid Job - training without data documentation
apiVersion: batch/v1
kind: Job
metadata:
  name: model-training-job
  namespace: development
  labels:
    job-type: model-training
    data-classification: confidential
    # ❌ MISSING: team label
  annotations:
    # ❌ MISSING: training-data-source
    # ❌ MISSING: data-anonymized (required for dev with confidential data)
    data-region-source: "eu-west-1"
    data-region-target: "us-east-1"
    # ❌ MISSING: cross-region-transfer-approved
spec:
  template:
    spec:
      containers:
      - name: training
        image: pytorch/pytorch:latest
        resources:
          requests:
            nvidia.com/gpu: "2"  # ❌ Exceeds development quota (max 1)
      restartPolicy: Never

---
# Invalid Service - cross-namespace reference
apiVersion: v1
kind: Service
metadata:
  name: external-model-ref
  namespace: ml-inference
spec:
  type: ExternalName
  externalName: secret-model.kube-system.svc.cluster.local  # ❌ Illegal cross-namespace